//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItems
    {
        public int CartItemID { get; set; }
        public int Quantity { get; set; }
        public int CartID { get; set; }
        public string EAN { get; set; }
    
        public virtual Carts Carts { get; set; }
    }
}
