//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotions
    {
        public int PromotionID { get; set; }
        public string Title { get; set; }
        public string EAN { get; set; }
        public decimal Discount { get; set; }
        public decimal DiscountPrice { get; set; }
        public System.DateTime ValidUntil { get; set; }
    }
}
