//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseUpdater_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carts
    {
        public int CartID { get; set; }
        public System.DateTime Expirationdate { get; set; }
    }
}
