//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseUpdater_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public string EAN { get; set; }
        public string Title { get; set; }
        public string Brand { get; set; }
        public string Shortdescription { get; set; }
        public string FullDescription { get; set; }
        public string Image { get; set; }
        public string Weight { get; set; }
        public decimal Price { get; set; }
        public string Category { get; set; }
        public string Subcategory { get; set; }
        public string SubSubcategory { get; set; }
    }
}
